version: '{branch}-{build}'
pull_requests:
  do_not_increment_build_number: false
skip_tags: true
os: Windows Server 2012 R2
install:
  - systeminfo | findstr /B /C:"OS Name" /C:"OS Version" /C:"System Type"
  - ps: Install-Product node 4.1.1 # Must match package.json
  - npm install -g npm@2.14.4 # Must match package.json
  - npm install || Echo First NPM install failed && npm install
  - node -v
  - npm -v
build: off
platform:
  - x86
  - x64
environment:
  COVERALLS_SERVICE_NAME: appveyor
  COVERALLS_REPO_TOKEN:
    secure: QkxS7B6UiQysk6aWhKHQd+36lKw/6pvjC9+wF4v/2RiD5wvoWi0kZJFrHFKpvPOK
  GITHUB_TOKEN:
    secure: X/JCTitKeibH9uTyAKi7ED04LT0qACHJonHNCuHVnBHA/GQtsFeNQea21K6QrLYy
  AWS_KEY:
    secure: pU5B2oAj+OUXmNTdZJvWsCQ34t3KbbtL+TIK6MsW0dM=
  AWS_TOKEN:
    secure: sk9Np49QKXFj5/tP0Vd0wA6I7GM+R7KY5QY1zztP1YtxCHnj7200DzNwdnrS6KgQ
test_script:
  - npm run test-coverage
  - npm run build-artifact
on_success:
  - npm run coveralls
artifacts:
  - path: download.txt
    name: Download Build (link within text file)
  - path: ./coverage/coverage-coffee.json
    name: Coffee-Coverage
# cache:
#   - node_modules -> package.json
